Team-ONY/TeamONY-Ogiri-Hub

.env.example

#3 
Closes #3 
- envファイルに格納すべき環境変数を記載したテンプレートファイルの作成
- 
- 
-

docs: 📄 envファイル内容のテンプレートの作成

---

src/main.jsx
src/theme/theme.js

Closes #9 
- main.jsxに定義されていたthemeをtheme.jsに一元化
- main.jsxでtheme.jsをインポートするように変更
- 
- 
-

Refactor/#9 main.jsxとtheme.jsで定義されていたthemeをtheme.jsに一元化

---

.github/ISSUE_TEMPLATE/feature_request_backend.md
.github/ISSUE_TEMPLATE/feature_request_frontend.md

Closes #11 
- feature_request(FE,BEどちらも)のaboutを更新
- 
- 
-

Docs/#11 feature_requestテンプレートのaboutを更新

---

package.json

Closes #16 
- lintをプロジェクト全体で走らせて、環境を変えたことによるDelete CRエラーの解消
- lintコマンドに--fixオプションの追加
- 
- 
-

style: lintを走らせて、Delete CRエラーを解消した

---

src/App.jsx
src/Icons/HomeIcon.jsx
src/Icons/LogoutIcon.jsx
src/Icons/ProfileIcon.jsx
src/Icons/TheadIcon.jsx
src/components/Auth/SignIn.jsx
src/components/Home.jsx
src/components/ui/Header.jsx
src/main.jsx

Closes #18 
- 仮のルーティング構築
- ヘッダー、サイドバーの実装
- 
- 
-

Feat/#18 ホームページの実装、仮のルーティング構築、ヘッダーの実装

---

src/App.jsx
src/Icons/TheadIcon.jsx
src/components/AdminPage.jsx
src/components/Auth/SignIn.jsx
src/components/Auth/SignUp.jsx
src/components/CreateThread.jsx
src/components/Home.jsx
src/components/Thread.jsx
src/components/ThreadDetail.jsx
src/components/ThreadList.jsx
src/components/ui/Header.jsx
src/config/firebase.js
src/services/threadService.js
src/services/userService.js

#20 
- スレッド関連の処理の大まかま実装
- 
- 
-

Feat/#19 スレッド関連機能の実装(未達成)

---

src/services/threadService.js

Closes #38 
- スレッド参加者人数の取得
- 
- 
-

fix: participantCountを追加し、participantsフィールドの配列の長さを取得するように修正

---

src/services/threadService.js

Closes #32 
- スレッドを作成した管理者はデフォルトでparticipantsフィールドに追加するように修正
- 
- 
-

fix: スレッド作成者はデフォルトでparticipantsに含めるように修正

---

src/components/CreateThread.jsx
src/components/ThreadDetail.jsx

Closes #41 
- ThreadList,CreateThreadからThreadに遷移させるためのボタンを実装した
- 
- 
-

feat/#41: ThreadList,CreateThreadからThreadに戻るためのボタンの実装

---

src/components/Thread.jsx
src/components/ThreadList.jsx

Closes #34
> もっと詳しく知りたい場合はコミット履歴からソースコードを見てね。
1. 検索語の管理:
- Thread.jsx で useState を使用して searchTerm を管理する。
- 検索入力欄の値が変わるたびに searchTerm を更新。
2. 検索語の適用:
- ThreadList.jsx で searchTerm を受け取り、スレッドをフィルタリングする。
- 各スレッドのタイトルと内容が searchTerm を含むかどうかをチェックし、一致するスレッドのみを表示。
```javascript
const filteredThreads = threads.filter((thread) => {
const titleMatch = thread.title.toLowerCase().includes(searchTerm.toLowerCase());
const contentMatch = thread.content.toLowerCase().includes(searchTerm.toLowerCase());
return titleMatch || contentMatch;
});
```
1. ソート順の管理:
- Thread.jsx で useState を使用して sortBy を管理する。
- ソートオプションが選択されるたびに sortBy を更新。
2. ソート順の適用:
- ThreadList.jsx で sortBy を受け取り、スレッドをソート。
- sortBy の値に応じて、以下の基準でソート:
- newest: 作成日時でソート（新しい順）
- popular: 参加者数でソート（多い順）
- commentCount: コメント数でソート（多い順）
```javascript …
```

feat/#34: スレッドの検索機能、ソート機能の実装

---

src/components/Thread.jsx

Closes #47 
- MenuListがTheadListのMotionBoxに重なって一部見えなくなっていたので、Portalでラップした
- 
- 
-

fix/#47: MenuListが重なって表示されない問題を解消

---

package-lock.json
package.json
src/App.jsx
src/components/HeroCard.jsx
src/components/Profile/AchievementCard.jsx
src/components/Profile/HallOfFameCard.jsx
src/components/Profile/ProfileMasonry.jsx
src/components/Profile/StatCard.jsx
src/components/Profile/UserInfoCard.jsx
src/components/ProfileEdit.jsx
src/components/ProfileStyles.css

#29 
- ユーザーIDの表示
- ユーザーの統計情報の表示(仮
- ユーザのアチーブメントの表示(仮
- ユーザーの殿堂入り投稿の表示(表示されなかった)
- 
-

feat/#29: 仮のプロフィール画面の実装

---

src/components/Home.jsx
src/components/Thread.jsx
src/components/ThreadList.jsx

Closes #
- 各ページでThreadListを呼び出すときにThreadListにlayoutを渡せるようにした
- Threadではgrid、Homeではlistにlayoutを渡してあげることで表示形式が変わるようにした
- 
- 
-

feat/#49: ThreadListをページによって表示形式を変えられるように実装

---

src/components/Thread/ThreadDetail.jsx

Closes #53 
- スレッド詳細にアクセスする前に参加チェックを追加
- ThreadDetailコンポーネントに参加チェックを追加
- 非参加ユーザーをスレッド一覧にリダイレクト
- 権限のないアクセスに対して警告メッセージを表示
- 
- 
-

fix/#53: スレッド詳細にアクセスする前の参加チェックの実装

---

.github/workflows/issue-auto-assign.yml
.github/workflows/pr-auto-assign.yml

fix: issueへの書き込み権限をissue,prのworkflowに付与

---

.github/workflows/pr-auto-assign.yml
src/components/Thread/CreateThread.jsx

- permission/pull-requestsにもwriteを付与
- 
- 
-

fix: pr-auto-assignの権限関連の修正

---

src/components/Thread/CreateThread.jsx

style/#64: CreateThreadのMotionBoxにThreadのMotionBoxと同じboxShadowプロパティを追加

---

src/components/Thread/ThreadDetail.jsx

Closes #54 
- コメント入力用のMotionBoxの透明度を変更し、後ろが透けて見えないように変更
- 
- 
-

style/#54: コメント入力MotionBoxの透明度を変更

---

src/components/Thread/ThreadDetail.jsx

- ThreadListのコメント入力のMotionBoxのスタイリングを修正して、画面下部に固定表示されるように修正
- 
- 
-

fix: 問題のMotionBoxのスタイリングを修正して、画面下部に固定表示されるように修正

---

src/components/Thread/ThreadDetail.jsx

Closes #76 
- URLがコメントされてるかのプログラムの追加
- 
- 
-

URLのコメントをさせない

---

package-lock.json
package.json
src/components/Admin/AdminRoute.jsx
src/components/Home/Home.jsx
src/components/Thread/ThreadDetail.jsx
src/components/Thread/ThreadList.jsx

Closes #80 
Closes #79 
Cleses #78
- ThreadDetailの読み込みの際のページネーションと無限スクロールの実装
- 過去のスレッドを遡ろうとすると最下部まで戻されるバグの修正
- 追加で、管理者画面にアクセスできないバグも発生したので、権限関連のロジックの変更
- 
- 過去のコメントが見れない問題の解決
- 読み込みが高速化したことによるUXの向上
- 
-

feat/#80(bug/#78,refac/#79): スレッドのコメント読み込みにページネーションと無限スクロールの実装+αの修正

---

src/components/Thread/CommentSection/CommentInput.jsx
src/components/Thread/CommentSection/CommentItem.jsx
src/components/Thread/CommentSection/index.jsx
src/components/Thread/ThreadDetail.jsx
src/components/Thread/ThreadHeader/AdminButton.jsx
src/components/Thread/ThreadHeader/index.jsx
src/components/Thread/hooks/useComments.js
src/components/Thread/hooks/useInfiniteScroll.js
src/components/Thread/hooks/useThreadData.js
src/index.css
src/utils/commentHelpers.js
src/utils/threadHelpers.js

Closes #82 
- ThreadDetailに含まれていた機能をできるだけモジュール化して、ThreadDetailに処理が集中しないように修正。可読性も向上した。
- 
- 
-

refactor/#82: ThreadDetailコンポーネントの可読性向上 & 各機能のモジュール化

---

src/Icons/LaughIcon.jsx
src/components/Home/Home.jsx
src/components/Thread/Ogiri/CreateOgiriButton.jsx
src/components/Thread/ThreadDetail.jsx

feat/#91: ThreadDetailいん

---

.env.example
package-lock.json
package.json
src/components/Thread/Ogiri/CreateOgiriEventModal.jsx
src/services/api.js

feat/#93: OgiriCreateModalにお題作成(テキスト、AI画像生成)、回答受付期間設定、イベント設定オプション(ユーザーごとの回答数など)、送信機能の実装 

---

src/components/Profile/UserInfoCard.jsx

アイコン編集のアバター編集のモーダル追加とデフォルトアイコン一覧のモーダル追加
- 
デフォルトのアバター設定
- 
- 
-

feat(front-end)/#105: アバター編集のモーダル追加(編集後の実装はまだ)

---

src/components/Thread/ThreadDetail.jsx
src/components/Thread/hooks/useComments.js

Closes #110 
- ThreadDetailでスレッドコメントのリアルタイム監視機能をFirestoreのonShapshotで実装
- useCommentsフックにコメントが重複して投稿させる冗長な箇所を発見したので削除
- 
- 
-

feat/#110: チャット機能をリアルタイムで反映させるように実装

---

src/components/Thread/Ogiri/OgiriAnswers.jsx
src/components/Thread/Ogiri/OgiriEvent.jsx
src/components/Thread/ThreadDetail.jsx
src/services/ogiriService.js

feat/#111: 大喜利イベント機能にリアルタイム監視機能の実装

---

src/components/Thread/Ogiri/OgiriEvent.jsx
src/services/ogiriService.js

Closes #112 
- 制限時間が過ぎたらフォームと回答ボタンのUIを無効化するように修正
- サーバーサイドでも制限時間のチェックを行い、APIを直接叩いても回答できないように修正
- 
- 
-

bug/#112: 制限時間が過ぎても回答を投稿できてしまう問題を修正

---

src/components/Thread/Ogiri/OgiriAnswers.jsx
src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #123 
- Firestoreのリアルタイムリスナーのみがリストの更新を担当するように修正
- 
- 
-

refactor/#123: 大喜利回答リストが新着順で表示されるように修正

---

src/components/Thread/Ogiri/CreateOgiriEventModal.jsx

Closes #121 
- 画像生成状態時にボタンのスタイルが変更されるように修正
- 画像生成ボタンは以前は生成時に非表示になる仕様だったが、常に表示するように変更、生成中はボタンの色をグレーに、ローディングアニメーションが表示されるように修正
- イベント作成ボタンも画像生成ボタンと同様の修正を行なった
- なし
- 視覚的にローディング状態がわかりやすくなるようになった
- 
-

refactor/#121: 画像生成ボタンとイベント作成ボタンのデザインを画像生成状態の時に視覚的にわかりやすく修正した

---

src/components/Thread/Ogiri/CreateOgiriEventModal.jsx

Closes #128 
- CreateOgiriEventModalがイベント作成後、またはモーダルを閉じた時にモーダルの状態が保持されてしまう問題を解決
- なし
- 
-

fix/#125: CreateOgiriEventModal を更新し、閉じる際およびイベント作成後にモーダルの状態をリセットする機能を追加。

---

src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #124 
- 大喜利イベントの入力フォームをCommentInputと同じ形式にデザインを変更した
- なし
- 
-

fix/#124: 🎨 OgiriEvent コンポーネントを改良し、テキストエリアとボタンのデザインを改善。

---

src/components/Profile/JoinedThreadCard.jsx
src/components/Profile/ProfileMasonry.jsx

-feat(front-end)/108： Profile画面に自分が参加しているスレッドを表示する
Closes #108 
- プロフィール画面に自分が参加しているスレッドを表示させた。
- 
- 
-

feat(front-end)/#108:Profile画面に自分が参加しているスレッドを表示する

---

src/components/Thread/CreateThreadModal.jsx

Closes #86 
- タイトルの文字数右に表示
- 
- 
-

feat: タイトルの文字数右に表示

---

src/components/Thread/CreateThreadModal.jsx

タグが無制限に指定、作成できてしまうので個数制限したい
Closes #52 
- タグの作成を５個に制限、タグ文字数は３０文字に制限した
- 
- 
-

feat(front-end)/#52:タグが無制限に指定、作成できてしまうので個数制限したい

---

README.md

Closes #143 
Closes #84
- プロジェクト用のREADMEをわかりやすくセクションを分けて更新。また、見た目も更新した。
- 
- 
-

docs: 📝 OgiriHubプロジェクト用のREADMEの更新

---

src/components/Thread/CreateThreadModal.jsx

bug: タグ入力の際に空入力ができてしまう
Closes #141 
- タグを空入力できないように修正
- トーストが出る判定をスレッド作成ボタンが押下された時に表示するように変更
- 
- 
-

fix/#141:タグ入力の際に空入力ができてしまう。

---

src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #147 
- イベントの制限時間が終了するまで他のユーザーの回答が閲覧できないように修正
- 
- 
-

fix/#147: 🐛 OgiriEventコンポーネントを更新し、イベントの有効期限に基づいて回答の表示を制御

---

src/components/Thread/CommentSection/CommentItem.jsx
src/components/Thread/CommentSection/index.jsx

Closes #155 
- コメントセクションの幅を上のThreadHeaderやCommentInputと同じ幅にして、レイアウトの一貫性を向上させた
- 
- 
-

style/#155: 🎨 コメントセクションの幅を上の要素と合わせてレイアウトの一貫性を向上

---

src/components/Profile/JoinedThreadCard.jsx
src/components/Profile/ThreadCard.jsx

Closes #157
- プロフィール画面にあるスレッドのリストにあるスレッドタイトルの色を変更
- 
- 
-

style/#157:プロフィール画面にあるスレッドのリストにあるスレッドタイトルの色を変更

---

index.html
src/index.css

Closes #150 
- アニメーションが適用されたアプリ全体の背景を静的な背景に変更し、パフォーマンス改善を図った
- 
- 
-

refac/#150: 🛠️ アニメーション背景を無効化し、パフォーマンスを改善

---

.github/ISSUE_TEMPLATE/bug_report.md

Closes #167 
- 何を記述するかの説明を記述した
- 毎回削除しなければならなかったところをコメントアウトした
- 
- 
-

docs: 📝 バグ報告テンプレートを改善し、詳細な説明や手順を記述するためのコメントを追加

---

src/components/Thread/ThreadDetail.jsx

Closes #186 
- creatorプロパティが必ず存在するように初期値を設定
- イベントデータの重複を防ぐ処理を追加
- 無効なイベントデータをフィルタリング
- 
- 
-

fix/#186: OgiriEventのcreatorプロパティ未定義を修正

---

src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #188 
- イベント終了時の最多投票回答取得ロジックを改善
- ベストアンサーの重複設定を防止
- 既存の目立つ表示デザインを維持
- 
- 
-

fix/#188: イベント終了時の最多投票回答表示の不具合を修正

---

src/components/Thread/Ogiri/OgiriAnswers.jsx
src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #185 
- OgiriAnswersコンポーネントで回答を新しい順に表示するためのソートロジックを追加
- OgiriEventコンポーネント内の回答ソート機能を更新し、重複を除外するロジックを改善
- 回答者の表示順を更新し、ユーザーインターフェースの一貫性を向上
- 
- 
-

refac/#185: 回答を日付の降順でソートする機能を追加

---

src/components/Thread/CreateThreadModal.jsx

Closes #163
- スレッド作成モーダルのUI全体の間隔を開けた。
- キャンセルボタンを作成
- 
- ![スクリーンショット 2025-01-15 163908](https://github.com/user-attachments/assets/50d20bec-ae91-4a8c-8186-db994cf11f62)
-

style/#163: スレッド作成モーダルのレイアウトを改善

---

src/App.jsx

Closes #196 
- アプリケーションのルートパス("/")にアクセスした際に"/home"へリダイレクトするルートを追加
- 不要なリダイレクトを削除し、ルーティングの一貫性を向上
- 
- 
-

fix: ルートパスのリダイレクトを追加

---

src/components/Thread/Ogiri/OgiriEvent.jsx

Closes #191 
- Framer Motionを使用したアニメーション実装
- フェードイン、スケール、スライドなどの複数のアニメーション効果
- グラデーションボーダーとラジアル背景エフェクト
- 要素ごとの段階的なアニメーション表示
- 
- 
-

feat/#191: ✨ 最多投票回答の表示アニメーションを追加

---

src/components/Thread/ThreadList.jsx

Closes #83
- ThreadListに自分がスレッドの管理者だった場合にマークが出現するように追加。
- 
- 自分から見た場合
- 他人から見た場合
-

feat/#83: ThreadListに表示される自分のスレッドに管理者マークを追加

---

src/components/Thread/ThreadList.jsx

- ThreadListの不要なコメントを削除
- 
- 
-

chore: ThreadListの不要なコメントの削除
